### ISSUE TITLE
Add basic components

### ISSUE THREAD

**Issue by matscats** [matscats/digital-processor#1]
Add the following components

* Register file
* ALU
* MUX
* Decoder
* Comparator

**Comment by Marcos7765** [comment]
Commencing issue. As disclosed in private, the comparator — and consequently the decoder — will be within the ALU. The decoder output shall be defining which component the inputs will be directed, but for such it is necessary either an tri-state driver* or some similar solution (putting every input bit in an AND gate with the decoder out prolly)

Edit: I've mixed up the decoder and tristate driver* (corrected from buffer) parts from the RF with the ALU's necessary components.

**Comment by Marcos7765** [comment]
Made the PR #8 for it
